/******************************************************************************
 *
 *      InvalidFormatException.java
 *
 *      Capgemini Confidential
 *      CG Source Materials
 *      © Copyright Capgemini 2017
 *
 *
 *******************************************************************************
 *
 *   Date....	WHO 	Description...............................................
 *	09/02/17	NR		First created
 *	
 ******************************************************************************/

package com.cg.bdd.utils;

public class InvalidFormatException extends Exception {

	// Generated by serialver from JDK 1.4.1_01
	static final long serialVersionUID = 8883328905089345791L;

	public InvalidFormatException() {
	}

	public InvalidFormatException(Throwable cause) {
		super(cause);
	}

	public InvalidFormatException(String message) {
		super(message);
	}
}